# (slug, A, B, faction, group)
PAIRS=[
("orgrimmar-thunder-bluff","Orgrimmar","Thunder Bluff","horde","horde"),
("orgrimmar-undercity","Orgrimmar","Undercity","horde","horde"),
("thunder-bluff-undercity","Thunder Bluff","Undercity","horde","horde"),
("stormwind-ironforge","Stormwind City","Ironforge","alliance","alliance"),
("stormwind-darnassus","Stormwind City","Darnassus","alliance","alliance"),
("ironforge-darnassus","Ironforge","Darnassus","alliance","alliance"),
("stormwind-dalaran","Stormwind City","Dalaran","alliance","alliance"),
("stormwind-auberdine","Stormwind City","Auberdine","alliance","alliance"),
("stormwind-theramore","Stormwind City","Theramore Isle","alliance","alliance"),
("orgrimmar-ratchet","Orgrimmar","Ratchet","horde","neutral"),
("stormwind-ratchet","Stormwind City","Ratchet","alliance","neutral"),
("orgrimmar-booty-bay","Orgrimmar","Booty Bay","horde","neutral"),
("stormwind-booty-bay","Stormwind City","Booty Bay","alliance","neutral"),
("orgrimmar-gadgetzan","Orgrimmar","Gadgetzan","horde","neutral"),
("stormwind-the-barrens","Stormwind City","The Barrens","alliance","neutral"),
("orgrimmar-mount-hyjal","Orgrimmar","Mount Hyjal","horde","new"),
("darnassus-mount-hyjal","Darnassus","Mount Hyjal","alliance","new"),
("undercity-riverglades","Undercity","Riverglades","horde","new"),
("stormwind-riverglades","Stormwind City","Riverglades","alliance","new"),
("thunder-bluff-zephras-isle","Thunder Bluff","Zephras Isle","horde","new"),
("stormwind-shendralas","Stormwind City","Shen'dralas","alliance","new"),
("orgrimmar-shendralas","Orgrimmar","Shen'dralas","horde","new"),
]
